### ISSUE TITLE
Coinbase - GetTicker

### ISSUE THREAD

**Issue by McxCZE** [ondra-novak/mmbot#21]
Hi, it seems that there is an issue with Coinbase. I think it is closely tied to how the market is acting right now, anyway it seems that they have a problem, based on user reports on Reddit. Some users are reporting: _When using Coinbase Pro API I am getting ESOCKETTIMEDOUT_

![image](https://user-images.githubusercontent.com/2656561/116187293-8ca23000-a725-11eb-9365-ac3448e3be1f.png)

And the Bot makes a ton of orders. 

![image](https://user-images.githubusercontent.com/2656561/116187471-e276d800-a725-11eb-89f1-1ac607e73de7.png)

**Comment by ondra-novak** [comment]
It seems, that issues was temporary because coinbase API was inaccessible. I can no longer reproduce this.

Every broker process (which handles communication with exchange) has limited time to handle each request. In case of timeout, the broker processes is killed and restarted.  In the most cases the situation is reported as exception, which is shown as exclamation symbol drawn inside of a red triangle (or yellow exclamation symbol for the command placeOrder). You can hover over symbol to see the error message.

About multiple orders, this can happen, when exchange's API fails to report opened orders (it returns no opened order, this isn't case of error, timeout or exception). This also happened on Binance during market overload. The bot eventually closes all extra opened orders once the API starts to report opened orders correctly. 

The most of these issues are tied to exchanges' APIs, especially when market is under stress. There is not much to do with it. You can temporary stop the bot using "Global Stop" button.
