### ISSUE TITLE
Trade detected, waiting for confirmation (ADJ Timeout)

### ISSUE THREAD

**Issue by mm185376** [ondra-novak/mmbot#25]
Hello, could you please assist us with the following error? At first, a friend of mine seen it with a real trader that was placing orders on markets, so I thought it was related to the used exchange. But now I'm also observing the same error on a trainer, so it could be some internal issue unrelated to brokers.
Thank you in advance!

![image](https://user-images.githubusercontent.com/66742253/135589456-18174f25-fd80-46ab-8586-0d8f4991ec03.png)

**Comment by Matasx** [comment]
_Sorry, I posted under incorrect account. I will keep updating under this account._ 

The error message now went away automatically, but the numbers seem a bit odd:
![image](https://user-images.githubusercontent.com/649216/135593824-ff208575-480c-4a50-876a-540b6f21dda3.png)

**Comment by ondra-novak** [comment]
The root cause of this message is difference between calculated position and position reported by the exchange/broker. 

It often happen, when the exchange has a technical difficulty to report new trades in time. So if this situation is detected, the trading is stopped until trade or timeout. 

This message can also appear when you withdraw the coin acting as the position, or any manually change in the (asset) balance without a trade. 

This can also happen with Trainer when you modify position in the trainer options. To speed up this process, you can specify timeout in settings (section misc)

I currently working on a better "leaked trade" detection especialy for spot markets
